### ISSUE TITLE
FileNotFound is begin a pain in my ass, plz help

### ISSUE THREAD

**Issue by JoeZwet** [JoeZwet/J4K-lwjgl#1]
heres the stack
```
[20:38:31] [main/INFO]: [STDERR]: java.io.FileNotFoundException: win32-x86_64\ufdw_j4k2_64bit.dll (The system cannot find the path specified)
[20:38:31] [main/INFO]: [STDERR]: 	at java.io.FileInputStream.open0(Native Method)
[20:38:31] [main/INFO]: [STDERR]: 	at java.io.FileInputStream.open(FileInputStream.java:195)
[20:38:31] [main/INFO]: [STDERR]: 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
[20:38:31] [main/INFO]: [STDERR]: 	at me.joezwet.kinect.utils.FileUtils.writeDlls(FileUtils.java:148)
[20:38:31] [main/INFO]: [STDERR]: 	at me.joezwet.kinect.utils.FileUtils.copyDllsToRun(FileUtils.java:141)
[20:38:31] [main/INFO]: [STDERR]: 	at me.joezwet.kinect.Kinect.<init>(Kinect.java:42)
[20:38:31] [main/INFO]: [STDERR]: 	at me.joezwet.kinectmc.Kinect.<init>(Kinect.java:10)
[20:38:31] [main/INFO]: [STDERR]: 	at me.joezwet.kinectmc.KinectMC.onInitialize(KinectMC.java:20)
```

**Comment by JoeZwet** [comment]
invalid after update
